//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abobaAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public PickupPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PickupPointID { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
